// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4NSo3kHRDXR96FsGC8h98XtcZ76uWjqo',
    appId: '1:199281240510:android:5860bb9b7d021e6d4371ef',
    messagingSenderId: '199281240510',
    projectId: 'ridelo25',
    databaseURL: 'https://ridelo25-default-rtdb.firebaseio.com',
    storageBucket: 'ridelo25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUYTG3n2_R5s9gB33lrti-5Zk8KSGxWg',
    appId: '1:199281240510:ios:abcdd84ef452bed84371ef',
    messagingSenderId: '199281240510',
    projectId: 'ridelo25',
    databaseURL: 'https://ridelo25-default-rtdb.firebaseio.com',
    storageBucket: 'ridelo25.firebasestorage.app',
    androidClientId: '199281240510-5l2s76oo50mg7jbse24fc7eep9d2u25r.apps.googleusercontent.com',
    iosClientId: '199281240510-77shmkir82djphurjslh6n471bun5l13.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupleDietFitness',
  );
}
